version: "3.9"

services:
  db:
    image: postgres
    container_name: banners_db
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql
      - ./scripts/postgres/v3/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/postgres/v3/fill_db.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - "5432:5432"
    networks:
      - banners-network
    deploy:
      restart_policy:
        condition: on-failure

  test-db:
    image: postgres
    container_name: banners_test_db
    restart: always
    env_file:
      - .env
    volumes:
      - ./scripts/postgres/v3/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/postgres/v3/fill_test_db.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - "5435:5432"
    deploy:
      restart_policy:
        condition: on-failure

  cache:
    env_file:
      - .env
    image: redis:alpine3.18
    container_name: banners_cache
    restart: always
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - cache-data:/data
    ports:
      - "6379:6379"
    networks:
      - banners-network
    deploy:
      restart_policy:
        condition: on-failure

  api:
    image: banners_api
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile
    container_name: banners_api
    volumes:
      - ./config/api.yaml:/config/api.yaml
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    networks:
      - banners-network
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  db-data:
  cache-data:

networks:
  banners-network:
    name: banners_network
    driver: bridge
